### ISSUE TITLE
kernel crash with AMD `gfx1035` device

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#134]
Hi @StRigaud ,

I'm just testing [this notebook](https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/20_image_segmentation/11_voronoi_otsu_labeling.html) by replacing `pyclesperanto_prototype` with `pyclesperanto` (version 0.8.1). The kernel dies when calling `voronoi_otsu_labeling` and there is no error message. I'm running on Windows 10. What other information do you need to reproduce this?

Thanks!

Best,
Robert

**Comment by haesleinhuepf** [comment]
I can narrow it further down: The error happens on an AMD GPU:

```
cle.get_device()
```
```
(OpenCL) gfx1035 (OpenCL 2.0 AMD-APP (3354.13))
	Type: GPU
	Compute Units: 6
	Global Memory Size: 12916 MB
	Maximum Object Size: 10523 MB
```

If I activate the NVidia GPU ,it works;
```
cle.select_device("RTX")
```

```
(OpenCL) NVIDIA GeForce RTX 3050 Ti Laptop GPU (OpenCL 3.0 CUDA)
	Type: GPU
	Compute Units: 20
	Global Memory Size: 4294 MB
	Maximum Object Size: 1073 MB
```

**Comment by StRigaud** [comment]
Can you try it with some intel device? To check if it only crashes on AMD device.

I do not have any AMD devices so this a blind spot for me.

**Comment by StRigaud** [comment]
From memory I already had issues with device named 'gfx1035' during workshop with users.

If it is not related to drivers and OCL installation, this may need to be debuged from the C++ side.

**Comment by haesleinhuepf** [comment]
Maybe we do it in an upcoming hackathon?

**Comment by StRigaud** [comment]
I renamed the issues for more explicite name related to the bug in case people use the search option for similar issues

**Comment by haesleinhuepf** [comment]
It's an AMD Radeon GPU, built into a Ryzen 9 6900HS CPU btw.

**Comment by StRigaud** [comment]
After some digging with @haesleinhuepf the issue is related to the cache system witht the call of 

```cpp
// saveBinaryToCache() OpenCL backend file
err = clGetProgramInfo(program, CL_PROGRAM_BINARIES, binary_vec.size(), &pointer_to_binary_vec, nullptr);
```

See [here}(https://community.amd.com/t5/archives-discussions/problem-with-clgetprograminfo-cl-program-binaries/td-p/139105) for possible lead to solve the issue

**Comment by haesleinhuepf** [comment]
Just for completeness: These are the things we modified during our mini-hackathon: https://github.com/clEsperanto/CLIc/compare/robert_screwing_up_things?expand=1

**Comment by StRigaud** [comment]
I push some code in https://github.com/clEsperanto/CLIc/tree/robert_screwing_up_things

I doubt if will change things because it is just a more complicated (c-style) way to do what I was already doing.
When you have 5 min to run, otherwise we can have a look at our next zoom
