### ISSUE TITLE
GPU device selection of devices that are not found

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#138]
... causes a warning and a different default-selection in cle-prototype compared to non-prototype. Maybe, we should make the selection case-insensitve?

To reproduce:
```
import pyclesperanto_prototype
import pyclesperanto

pyclesperanto_prototype.select_device('rtx')

pyclesperanto_prototype.select_device('RTX')

pyclesperanto.select_device('rtx')

pyclesperanto.select_device('RTX')
```

![image](https://github.com/clEsperanto/pyclesperanto/assets/12660498/7aa7068f-137f-41af-b99b-d4469c0b3b6a)

**Comment by StRigaud** [comment]
Indeed, I am case sensitive.

Should be fix at the next update

**Comment by StRigaud** [comment]
FYI: it is also possible to select devices by index (starting from 0 for the first one). Based on the return list of the `cle.list_avaialbe_devices()`

example:
```
cle.select_device(0)
```

I did this because both my GPUs have the same name.

**Comment by StRigaud** [comment]
Quick question: is device is not found it should normally take the last one available in the device list. which, if i remember well, what the prototype is doing also no?

**Comment by haesleinhuepf** [comment]
I interpret [this code](https://github.com/clEsperanto/pyclesperanto_prototype/blob/413e3fadbff7d5db07c98d614cd5e2d2a94ae38c/pyclesperanto_prototype/_tier0/_device.py#L120) and [this code](https://github.com/clEsperanto/pyclesperanto_prototype/blob/413e3fadbff7d5db07c98d614cd5e2d2a94ae38c/pyclesperanto_prototype/_tier0/_device.py#L75C14-L75C28): in case no device with the name, it lists all devices and takes the last one in the list.

Also, it spits out [a warning](https://github.com/clEsperanto/pyclesperanto_prototype/blob/413e3fadbff7d5db07c98d614cd5e2d2a94ae38c/pyclesperanto_prototype/_tier0/_device.py#L77).

**Comment by StRigaud** [comment]
You use a `sorted` function which is don't how it sort and this may be the main thing that change the default device returned.

On my side, I simply request the devices and store them in a vector as they come. So the order is purely based on what OpenCL request the devices.
I can introduce a sorting process before, be we would need to decide on a how, and also if it is really that usefull?

I would prefere to encourage user to select their device, even though we indeed whant a default selection.

**Comment by StRigaud** [comment]
done with #157
