### ISSUE TITLE
cle.imread is missing in API (and I think that's good)

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#140]
... we just need to document this somewhere.

It originally existed (in the prototype) to have the same image-loading call work in ImageJ and in Python.

**Comment by StRigaud** [comment]
it is indeed on purpose, I am not in favor of adding it neither.

We can create a deprecated function for python, with a warning message.

**Comment by haesleinhuepf** [comment]
> We can create a deprecated function for python, with a warning message.

Yes, good idea!
