### ISSUE TITLE
'erode_labels' is missing an argument `relabel_islands`

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#141]
Compared to the prototype-version, the function `erode_labels` has missing an argument `relabel_islands`.

Notebook to try it out:
https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/20h_segmentation_post_processing/open_close_labels.html

**Comment by StRigaud** [comment]
`relabel_island` parameter was renamed `relabel`.

The reason is that the operation behind is a simple sequantial relabeling, the `island` par is therefore miss leading.
We can put it back as it was if it make more sense

**Comment by haesleinhuepf** [comment]
ok, awesome, that makes sense!
