### ISSUE TITLE
'connected_components_labeling_box' missing in API

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#142]
... and I think it makes sense. We need to document it though in the transition notes....

**Comment by StRigaud** [comment]
now `connected_components_labeling`, connectivity is a parameter.

If accepted, will be propagated to other filters and function which depends on connectivity

**Comment by StRigaud** [comment]
related with clesperanto/CLIc#211

All '_box', '_sphere', and '_diamond'  suffix are removed and replaced by a `connectivity` parameter with default value to 'box'.
Introduced with:
- #177
