### ISSUE TITLE
`exclude_small_labels` and `exclude_large_labels` are missing in the API

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#143]
... and it would be great if we could have them, They are quite useful.

Notebook to play with it:
https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/20h_segmentation_post_processing/select_labels_based_on_size.html

**Comment by haesleinhuepf** [comment]
This requires to implement `exclude_labels_out_of_size_range` ... and this requires implementing #145 first: https://github.com/clEsperanto/pyclesperanto_prototype/blob/413e3fadbff7d5db07c98d614cd5e2d2a94ae38c/pyclesperanto_prototype/_tier3/_exclude_labels_outside_size_range.py#L31

**Comment by StRigaud** [comment]
requires to close #145 first

**Comment by StRigaud** [comment]
Filters are now available in pyclesperanto
