### ISSUE TITLE
Should a CPU be found on an M2 macbook?

### ISSUE THREAD

**Issue by m-albert** [clEsperanto/pyclesperanto#149]
I'm on a macbook with an M2 and 
```python
import pyclesperanto as cle
devices = ['all', 'cpu', 'gpu']
{device: cle.list_available_devices(device_type=device)
     for device in devices}
```
gives: 
> Warning: Fail to find 'cpu' OpenCL compatible devices.
`{'all': ['Apple M2'], 'cpu': [], 'gpu': ['Apple M2']}`

**Comment by StRigaud** [comment]
After a quick search, we get the same behaviour from `pyopencl` package. So I think its normal that no `cpu` are found.

This may change if we manage to switch to Metal for OSx users.
Closing until then.
