### ISSUE TITLE
[Feature] cle.execute is missing in API

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#156]
**Is your feature request related to a problem? Please describe.**

I would like to execute custom kernels, like using `pyclesperanto_prototype.execute`. 

**Describe the solution you'd like**

It would be great to make [this CLIc function](https://github.com/clEsperanto/CLIc/blob/620c17ee82c2b53f1ec8701257e9eb656395ce5b/clic/src/execution.cpp#L193) available in the pyclesperanto API, ideally matching [this function's API](https://github.com/clEsperanto/pyclesperanto_prototype/blob/413e3fadbff7d5db07c98d614cd5e2d2a94ae38c/pyclesperanto_prototype/_tier0/_execute.py#L2).

**Additional context**
The cle.execute function is key for getting all the neighborhood-/graph-filters out of pyclesperanto

**Comment by StRigaud** [comment]
`execute` should mimic now the protoype execute function. Additionnaly, kernel source can now be passed either as a file (.cl) or as a string.
