### ISSUE TITLE
[Feature] Bia-bob compatibility

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#159]
**Is your feature request related to a problem? Please describe.**
It would be cool if [bia-bob](https://github.com/haesleinhuepf/bia-bob), a large-language-model-based coding assistant, could propose pyclesperanto to users in case it's installed. It uses a plugin-system, which we could program an adapter for here. 

**Describe the solution you'd like**
We need to adapt [this commit](https://github.com/clEsperanto/pyclesperanto_prototype/pull/327/commits/3c63a21b7231f8fd6bde89495b29def4fc5595e0) from the _prototype. This should be pretty straight-forward as most of it is auto-generated. 

We _may_ make the [code generator](https://github.com/clEsperanto/pyclesperanto_prototype/blob/3c63a21b7231f8fd6bde89495b29def4fc5595e0/demo/interoperability/generate_bia_bob_connector.ipynb) part of [gencle](https://github.com/clEsperanto/gencle). I'm looking forward to hear your opinion @StRigaud .

**Additional context**

**Comment by StRigaud** [comment]
Can we close this now that #246 is merged?
