### ISSUE TITLE
[Bug] bounding_box() on uint8 data is limited to values < 256

### ISSUE THREAD

**Issue by thawn** [clEsperanto/pyclesperanto#164]
**Pre-requist tasks**
- [x] My device drivers are up to date.
- [x] The [troublemaking solutions](https://github.com/clEsperanto/pyclesperanto?tab=readme-ov-file#troubleshooting-graphics-cards-drivers) did not solved my issue.

**Describe the bug**
the results of bounding_box() on a uint8 image are limited to uint8 values. Any value that should be above 255 becomes 255

this is particularly annoying, because threshold_otsu returns uint8 images

**To Reproduce**
``` python
import pyclesperanto as cle
import pyclesperanto_prototype as clep
import numpy as np

#create sample image
image = np.zeros((300, 300), dtype=np.uint8)
image[240:290, 20:260] = 1

#measure the bounding box with pyclesperanto
cle.bounding_box(image) # returns [20.0, 240.0, 240.0, 255.0, 255.0, 1.0]

#measure the bounding box with pyclesperanto_prototype
clep.bounding_box(image) # returns [20.0, 10.0, 0, 259.0, 29.0, 0]

**Expected behavior**
the results of bounding_box() should be independent of the image data type (I guess uint32 should be the default return data type)

**Configuration details:**
 - OS: [e.g. MacOS 12.7.2]
 - Device: [Apple M1 Max]
 - Device type: [Integrated GPU]

**Comment by thawn** [comment]
Cool thanks, Stephane 🎉

**Comment by thawn** [comment]
just noticed that the bug is fixed for the x coordinate but still persists for the y and z coordinates.

I guess you need to apply similar changes for y and z as you did for x [in this commit](https://github.com/clEsperanto/CLIc/commit/7efff169d497f01a48aa4f58184b40df82648b19#diff-6924482ccfa866d505747ba1670cc4dccf14e6500cc4296d2b9f571ed37eb5a9)

**Comment by thawn** [comment]
@StRigaud would you prefer to reopen this bug, or should I file a new one?

**Comment by thawn** [comment]
actually, I suggest to fix the bug in [line 17 of tier1::multiply_image_and_position_func()](https://github.com/clEsperanto/CLIc/blob/master/clic/src/tier1/multiply_image_and_position.cpp#L17) rather than creating an output array of the same type as the input, that function should create an output that can handle positions larger than 255 (e.g. at least uint32 if the input is an integer and float32 or float64 if the input is a float).

**Comment by StRigaud** [comment]
`uint64` and `int64` are not supported in OSx arm64 so I would enforce 32 bits as much as possible for now.
