### ISSUE TITLE
[Bug] the documentation fo bounding_box() is wrong

### ISSUE THREAD

**Issue by thawn** [clEsperanto/pyclesperanto#165]
**Pre-requist tasks**
- [x] My device drivers are up to date.
- [x] The [troublemaking solutions](https://github.com/clEsperanto/pyclesperanto?tab=readme-ov-file#troubleshooting-graphics-cards-drivers) did not solved my issue.

**Describe the bug**
The Docstring of bounding_box says:

```text
Determines the bounding box of all nonzero pixels in a binary image. If called
from macro, the positions will be stored in a new row of ImageJs Results table
in the columns 'BoundingBoxX', 'BoundingBoxY', 'BoundingBoxZ',
'BoundingBoxWidth', 'BoundingBoxHeight' 'BoundingBoxDepth'.In case of 2D images
Z and depth will be zero.
```

However, the results are 'BoundingBoxXStart', 'BoundingBoxYStart', 'BoundingBoxZStart',
'BoundingBoxXEnd', 'BoundingBoxYEnd', 'BoundingBoxZEnd'

I think the algorithm is fine as it is, since it allows to use the results for slicing the image without further calculations. However, the documentation should be changed according to the algorithm

**To Reproduce**
```python
cle.bounding_box()
```
**Expected behavior**

The Docstring should be (or similar):
```text
Determines the bounding box of all nonzero pixels in a binary image. If called
from macro, the positions will be stored in a new row of ImageJs Results table
in the columns 'BoundingBoxXStart', 'BoundingBoxYStart', 'BoundingBoxZStart',
'BoundingBoxXEnd', 'BoundingBoxYEnd', 'BoundingBoxZEnd'. In case of 2D images
Z and depth will be zero.
```

**Comment by thawn** [comment]
Cool thanks, Stephane 🎉

**Comment by StRigaud** [comment]
Will be effective in the next release
