### ISSUE TITLE
Projection operation are very slow

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/pyclesperanto#19]
When benchmarking the histogram I have notice that pyclesperanto is very slow.
I identified the issue to the SumYProjection operation at the end to sum the partial histogram into a final one.

Projection (minimum, maximum, and sum) are costly without any good reason. 
We need to solve this issue.

Possible things to check:
- Only tested Y and Z direction, is it the same for X?
- Is the GlobalNDRange correct?

Projection kernels are very basics, I fail to understand why they can be so slow ...

**Comment by haesleinhuepf** [comment]
I just saw that 
* `maximum_z_projection` on a 3D image returns a 3D image and
* `maximum_of_all_pixels` on a 2D image returns a 2D image.

Is it possible that the projection are computed many many times because the projected image does not have one dimension less than the original image? That might explain why it's slow...

**Comment by StRigaud** [comment]
I think there are multiple issues here.

I solve it for he histogram, the problem was coming from the output shape which is, by default, the same as the input.
```python
    @plugin_function
    def histogram(self, input_image: Image, output_image: Image = None, bins : int = 256):
        from ._pyclic import histogram as op
        op(self._gpu, input_image, output_image, bins)
        return output_image
```
However this is not the case for the histogram which return shape is a 1d array of size equals the number of bins. Adding the
line
```python
        output_image = self.create([bins])
```
greatly improve the overall speed of the function.


For operation like `sum_?_projection` etc. I believe we need to adapt the output shape properly. For example, if applying a `sum_y_projection` on a 2D data `(Y,X)` the output return should be a 1D array `(X)` and not a 2D array `(1,X)` which is the case currently.

Finally, a projection along Z on a 2D data still take more time than it should. The operation will still make a run for all (x,y) pixels even though the Z dimension is empty. A test on dimension could prevent this useless run.

**Comment by StRigaud** [comment]
will reopen when benchmarking will be the main topic
