### ISSUE TITLE
[Bug] Affine transform: parameter names changed compared to the prototype

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#196]
**Pre-requist tasks**
- [ ] My device drivers are up to date.
- [ ] The [troublemaking solutions](https://github.com/clEsperanto/pyclesperanto?tab=readme-ov-file#troubleshooting-graphics-cards-drivers) did not solved my issue.

**Describe the bug**
A clear and concise description of what the bug is. What were you trying to do and what happened.

When updating [this notebook](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/benchmarks/affine_transforms.ipynb) to use pyclesperanto without prototype, I receive error messages, because parameter names changed.

transform -> transform_matrix
linear_interpolation -> interpolate

**To Reproduce**
Steps to reproduce the behavior, ideally a notebook ready to run, with test data, at minima a code snippet.

**Expected behavior**
A clear and concise description of what you expected to happen. Mainly if the issues is not a crash but a bad behaviour of a filter or operation.

I would attempt to avoid backwards compatibility breaking changes. It's otherwise harder to update code.

**Screenshots**
If applicable, add screenshots to help explain your problem. Expected results, vs actuall results. Or the output error message if any.

**Configuration details:**
 - OS: [e.g. MacOS 14, Windows 11, Linux Ubuntu 22.03]
 - Device: [e.g. NVIDIA RTX 4090, Intel Iris Graphics, etc.]
 - Device type: [e.g. Integrated GPU, dedicated GPU, CPU, HPC server]

**Additional context**

**Comment by haesleinhuepf** [comment]
Also the transform_matrix parameter does not accept numpy arrays. It expects a list.

**Comment by StRigaud** [comment]
>transform -> transform_matrix
linear_interpolation -> interpolate

I prefer my parameter name:
transform_matrix -> specify we expect the transform matrix, not a AffineTransform3D or AffineTransform object like in the prototype
interpolate -> currently a bool, can easily be changed for a string if one day we add other type of interpolation (I doubt but we dont know), and its shorter to type.

I can do a `deprecated` message though

> Also the transform_matrix parameter does not accept numpy arrays. It expects a list.

Not sure I can change that for now, I do not have access at Numpy API on the C++ side.

**Comment by StRigaud** [comment]
documentation was updated [here](https://clesperanto.github.io/pyclesperanto/prototype.html#affine-transform) and a deprecated function will be introduced with #197
