### ISSUE TITLE
[Bug] set_wait_for_kernel_finish in Prototype was renamed to cle.set_wait_for_kernel_to_finish

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#198]
**Pre-requist tasks**
- [ ] My device drivers are up to date.
- [ ] The [troublemaking solutions](https://github.com/clEsperanto/pyclesperanto?tab=readme-ov-file#troubleshooting-graphics-cards-drivers) did not solved my issue.

**Describe the bug**
A clear and concise description of what the bug is. What were you trying to do and what happened.

When updating [this notebook](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/benchmarks/affine_transforms.ipynb) to use the non-prototype version of clesperanto, I noticed that set_wait_for_kernel_finish in Prototype was renamed to set_wait_for_kernel_to_finish.

**To Reproduce**
Steps to reproduce the behavior, ideally a notebook ready to run, with test data, at minima a code snippet.

**Expected behavior**
A clear and concise description of what you expected to happen. Mainly if the issues is not a crash but a bad behaviour of a filter or operation.

I would attempt to avoid backwards compatibility breaking changes. It's otherwise harder to update code.

**Screenshots**
If applicable, add screenshots to help explain your problem. Expected results, vs actuall results. Or the output error message if any.

**Configuration details:**
 - OS: [e.g. MacOS 14, Windows 11, Linux Ubuntu 22.03]
 - Device: [e.g. NVIDIA RTX 4090, Intel Iris Graphics, etc.]
 - Device type: [e.g. Integrated GPU, dedicated GPU, CPU, HPC server]

**Additional context**

**Comment by StRigaud** [comment]
Was supposed be already taken care off with the `interoperability` alias:
https://github.com/clEsperanto/pyclesperanto/blob/a3896ccb4e06ab4cd7b7cee47a576e6a4869198a/pyclesperanto/_interroperability.py#L19C2-L19C78

will push a patch
