### ISSUE TITLE
Improve wrapper output module

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/pyclesperanto#2]
This current package rely on [pyBind11](https://pybind11.readthedocs.io/en/stable/) wrapping around [CLIc](https://github.com/clEsperanto/CLIc_prototype).

We do not wrap the entire C++ library only the top classes and functions that Python need to know about:

- cleGPU class
- cleObject class
- Tier1 kernels has a set of functions
- Tier2 kermels has a set of functions
- etc.

All are added as part of a module called [_pyclesperanto](https://github.com/clEsperanto/pyclesperanto/blob/ee471bc949529e7a6ec7814d4cd9b39274967fed/pyclesperanto/pyclesperanto.cpp#L6-L10) which will generate a python `.so` library which is then imported by the package [pyclesperanto](https://github.com/clEsperanto/pyclesperanto/blob/ee471bc949529e7a6ec7814d4cd9b39274967fed/pyclesperanto/__init__.py#L1-L6)

From the python side, current usage can be observed in the [test_pyclesperanto.py](https://github.com/clEsperanto/pyclesperanto/blob/0bc2bc8eebaf40b466fe99d0ae56b4928b31201a/tests/test_pyclesperanto.py#L5-L19)

```python
import pyclesperanto as cle

# declare an instance of the class gpu
gpu = cle.gpu() 

# the gpu class is in charge of creating, push, and pull operation.
buffer_input = gpu.push() 
buffer_output = gpu.create() 

# tier 1, and other kernel are directly called from the pyclesperanto module as function
# WARNING: the function requires the gpu object as first argument
cle.add_image_and_scalar(gpu, buffer_input, buffer_output, 100)

# the gpu class is in charge of creating, push, and pull operation.
result = gpu.pull(buffer_output)
```

Though it is usable like this, it is not user friendly nor respecting the clEsperanto API usage. We would need a python top layer equivalent to the [gateway class in CLIc](https://github.com/clEsperanto/CLIc_prototype/blob/master/clic/include/core/clesperanto.hpp).
Mainly we want to take advantage of the numpy package which, in one object, provide the data, the type, and the shape. We may want to insure that data are loaded as `(xyz)` and not `(zyx)` and etc.

The wrapper is not a fix thing, the goal is to update this repo in order improve the wrapping python output around the back-end and extend a python layer on top of it for users.

**Comment by StRigaud** [comment]
I have create a [notebook](https://github.com/clEsperanto/pyclesperanto/blob/main/demo/raw_c%2B%2B_to_python_wrapper_API_example.ipynb) displaying all the various current usage of the raw wrapped c++ classes, without any python API layers.

Two PR already propose a first and a more advance API example:
- #8 
- #9 

If we aim for the pimped version, 
- What do we need to do to improve a bit more the API
- What is needed from the C++ side to allows or facilitate those improvements

Currently the C++ side already managed some Python visible aspect such as the shift in shape order (zyx <-> xyz) and already squeeze the return numpy shape if dimension size is 1.

Do we want to actually to the less as possible from the C++ wrapper side and leave it to pure python API layer or the oposite, what ever the C++ side can do, it does and the rest is left to python?
Am I asking too much existential question ?

**Comment by haesleinhuepf** [comment]
Hey Stephane @StRigaud ,

the notebook looks fantastic! It's just a bit too technical though. Shall I set up a notebook processing blobs.tif (blur, threshold, voronoi-otsu-labeling)? That might be more visual ;-)

Thanks!
Robert

**Comment by StRigaud** [comment]
Thanks @haesleinhuepf 

The notebook is made to be technical ;) It aim to show the pybind11 module API at is base for you and for others that may want to participate into the wrapper technical part and API design.

On top of it, we  then put a pure python layer (aka your [pimped API](https://github.com/clEsperanto/pyclesperanto/pull/9) for a start) and build up the user API from there.
I will then add up a more user-friendly notebook with some blobs, gaussian blur, labeling and so on :rocket: 

However I would be interested to have your opinion on the CLEarray class i proposed in my [previous post](https://github.com/clEsperanto/pyclesperanto/issues/2#issuecomment-1105233507)

**Comment by StRigaud** [comment]
Except for core functionality, specific python operator and behavior, all tiers operation are now autogenerated
