### ISSUE TITLE
Kernel wishlist

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#20]
Hi Stephane @StRigaud ,

I'm just attempting to implement some basic workflows and some operations are missing. I'll list them here and would consider them as high priority. These are not necessary before I2K, but nice to have.

* `subtract_image_from_scalar` for inverting an image
* `dilate_labels` for segmenting the rim of nuclei
* `multiply_images`
* `divide_images`

I'll extend that list in the coming days.

No rush!

**Comment by StRigaud** [comment]
> `subtract_image_from_scalar` for inverting an image

Isn't this the same as add image and scalar but with a negative value for the scalar?

> * `dilate_labels` for segmenting the rim of nuclei
> 
> * `multiply_images`
> 
> * `divide_images`

I am on it :)

**Comment by StRigaud** [comment]
Done, all kernel are available on the CLIc side (WARNING, not tested), we just need to update the submodule link.

But I have some questions:

- Difference between `subtract_image_from_scalar` and `add_image_and_scalar` with a negative value?
- Difference between `dilate_labels` and `extend_labeling_via_voronoi` (dilate has a radius criteria but that's it) ?

**Comment by haesleinhuepf** [comment]
> * Difference between `subtract_image_from_scalar` and `add_image_and_scalar` with a negative value?

Assume you want to inverte an 8-bit integer image: `255 - x`. You cannot do that with `add_image_and_scalar` unless you create an image with all pixels `=255`, which is computationally wasteful.

> * Difference between dilate_labels and extend_labeling_via_voronoi (dilate has a radius criteria but that's it) ?

Yes, `dilate_labels` has a maximum radius; `extend_labeling_via_voronoi` fills the whole image.

**Comment by StRigaud** [comment]
> Yes, `dilate_labels` has a maximum radius; `extend_labeling_via_voronoi` fills the whole image.

So we could simply replace the `extend_labeling_via_voronoi` by the `dilate_labels` with a ridiculous high radius (or alternative flag) 

Just saying as I don't know if `extend_labeling_via_voronoi` is easier to understand than `dilate_labels` to maximum?

Maybe a discussion for an other time :)

**Comment by haesleinhuepf** [comment]
Yes, and good names for functions are always welcome! 🌞

**Comment by StRigaud** [comment]
kernels are now available
