### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by guijacquemet** [clEsperanto/pyclesperanto#233]
Simply tell use what bother you, we are here to help!

Hi, 
Thanks for the awesome toolbox.
How should I cite pyclesperanto when used in a publication?

Thanks

Guillaume

**Comment by haesleinhuepf** [comment]
Hi Guillaume,

great question! It depends on which version you were using. If you were using the code here in this repository, you could cite it like this:

```
Stéphane Rigaud, Robert Haase (2024) pyclesperanto. Github repository. https://github.com/clEsperanto/pyclesperanto/releases/tag/0.12.1 
```
(make sure to specify the exact version you used for optimal reproducibilty)

If you were using `pyclesperanto_prototype`, you can cite the right version on Zenodo, which comes with a DOI, Example: 
```
Robert Haase, Pradeep Rajasekhar, Talley Lambert, grahamross123, Juan Nunez-Iglesias, Lachie, Clement Caporal, Christophe Avenel, ENicolay, & Elissavet. (2023). clEsperanto/pyclesperanto_prototype: 0.24.2 (0.24.2). Zenodo. https://doi.org/10.5281/zenodo.10432619
```

And if you were using the graphical user-interface in Fiji to generate Python code, you could cite this preprint:
```
Robert Haase, Akanksha Jain, Stéphane Rigaud, Daniela Vorkel, Pradeep Rajasekhar, Theresa Suckert, Talley J. Lambert, Juan Nunez-Iglesias, Daniel P. Poole, Pavel Tomancak, Eugene W. Myers (2020) Interactive design of GPU-accelerated Image Data Flow Graphs and cross-platform deployment using multi-lingual code generation
bioRxiv 2020.11.19.386565; doi: https://doi.org/10.1101/2020.11.19.386565
```

@StRigaud please correct me if I'm wrong with any of the above. And btw. with the next release of `pyclesperanto`, it will also create a record on Zenodo. We can then use the citation scheme from there like with the prototype.

Best,
Robert

**Comment by StRigaud** [comment]
@haesleinhuepf is possible to put the entire organization as a zenodo instead of just repos?

**Comment by haesleinhuepf** [comment]
> That's means we should also have a zenodo for all repo with deployement (CLIc, PyClesperanto, ClesperantoJ, and CLIJ3) no ?

Is also activated as of today! For CLIc it was already. Btw. you should also be able to do [this](https://zenodo.org/account/settings/github/).

**Comment by guijacquemet** [comment]
I am using detectLabelEdges, so I guess I need to cite pyclesperanto-prototype.
Thanks

**Comment by StRigaud** [comment]
If I'm not mistaken the function is also available in pyclesperanto 😄

**Comment by StRigaud** [comment]
A Zenodo DOI have been added now for citing
