### ISSUE TITLE
[Bug] pre-commit makes pointless changes all the time causing merge conflicts

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#234]
**Pre-requist tasks**
- [x] My device drivers are up to date.
- [x] The [troublemaking solutions](https://github.com/clEsperanto/pyclesperanto?tab=readme-ov-file#troubleshooting-graphics-cards-drivers) did not solved my issue.

**Describe the bug**
I am trying to work on the python code in this repository. Whenever I commit something to an existing PR, the github CI interferes with my changes, causing merge conflicts with every second commit I make.

**To Reproduce**
1. Create a pull request from a new branch. 
2. Modify code, e.g. add functions, edit `__init__.py` files
3. Commit the change
4. Continue working, add more functions and code
5. Commit the change
6. A merge conflict occurs

**Expected behavior**

I think the this is not a pre-commit, as the modifications by the CI obviously happen post-commit. I am proposing to turn this feature entirely off, or to execute it when merging the PR (commit to main branch), not with every commit.

**Screenshots**

The current workflow would work, if I wait 5 minutes between step 3 and 4, which is a waste of time obviously. Typically, the CI does changes like these:

![image](https://github.com/user-attachments/assets/f18204a1-3cea-46a4-9d46-a254a01817cf)

If these are the only changes (reordering imports) I can also very conveniently live without this precommit.ci

**Configuration details:**
 - OS: [e.g. MacOS 14, Windows 11, Linux Ubuntu 22.03]
 - Device: [e.g. NVIDIA RTX 4090, Intel Iris Graphics, etc.]
 - Device type: [e.g. Integrated GPU, dedicated GPU, CPU, HPC server]

**Additional context**

I struggled multiple times while working on #232 you can see in the history of that PR how the CI and I are fighting against each other.

**Comment by StRigaud** [comment]
You can put ```# isort:skip``` in front of the line you do not want to be `updated` by `isort` which auto-sort import statement.

Can be tricky at first but help keep it clean. If really annoying, I will remove

**Comment by StRigaud** [comment]
The pre-commit enforce the following:
- import order (with overwrite using `# isort:skip`)
- black auto-formating
- a maximum line length 
- clean-up invisible changes (e.g. end-of-line spaces, trailling return, yaml and json wrong formating/indentation)

I agree these are not major updates but it maintains a clean code while avoiding people the pain to install or master this ecosystem.
You can install `pre-commit` locally and it will act before you actually commit. Making it more immediat change. See [docu](https://pre-commit.com/#install), though you still might not like it :)

I will remove it for now, but I would like to keep this kind of cleanup checks to ensure clean code. I am open to alternatives if you have some in mind.

**Comment by StRigaud** [comment]
Done

**Comment by haesleinhuepf** [comment]
Awesome, thanks! Again, I think it's cool to do this e.g. when merging into main, but not with every push on a branch.

**Comment by StRigaud** [comment]
I think I can configure it for `pre-merge-commit` but I do not know how it will interact with github PR merge. So I will need to test.
