### ISSUE TITLE
Many functions in interoperability.py are lacking a "device" parameter

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#261]
Is this intentional @StRigaud ?

[_interoperability.py](https://github.com/clEsperanto/pyclesperanto/blob/main/pyclesperanto/_interroperability.py)

**Comment by StRigaud** [comment]
This is a python only list of function and aliases where I did some quick fix and update to fit python, bumpy, and prototype.

This a dirty but easy to use place for interoperability fixes.

**Comment by StRigaud** [comment]
After discussion, lets remove or reduce implementation in interoperability to stric minimum
