### ISSUE TITLE
The histogram function is missing a parameter `determine_min_max`

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#264]
... which it had in the _prototpye. This is what it does:

https://github.com/clEsperanto/pyclesperanto_prototype/blob/8bd12efd32d2bcdbfc859bcfec85c7a567e17b06/pyclesperanto_prototype/_tier3/_histogram.py#L93-L95

I'm ok with not implementing this, but it must go in the transition guide document otherwise.

**Comment by StRigaud** [comment]
did not see the use of the parameter, ok to put it in the transition guide

**Comment by haesleinhuepf** [comment]
> did not see the use of the parameter

It's user friendly, because it allows you to determine a histogram without the need to determine min and max before. It's the default in tools like ImageJ ;-)

**Comment by StRigaud** [comment]
> It's user friendly, because it allows you to determine a histogram without the need to determine min and max before. It's the default in tools like ImageJ ;-)

Yeah, but if you do not provide the min or max, the histogram recompile them already. I find this redondant with default value (on the python side, they are marked as `Optionnal`) , and unclear for the user actually as is allows to overwrite parameter provided by the user.

It can make sense in ImageJ though as it has a GUI, this is not the case for pyclesperanto.

**Comment by haesleinhuepf** [comment]
> , the histogram recompile them already.

❤️
