### ISSUE TITLE
Add the package into a package manager (conda, pip, ...)

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/pyclesperanto#3]
No experience into this, especially with C++, Wrapper, scikit-build, OpenCL mix!

Basically, how can we make this work by simply calling 
```
conda install pyclesperanto
```
or
```
pip install pyclesperanto
```

No clue what is needed nor how to do this, but still happy to help into this.

**Comment by StRigaud** [comment]
Save for later, tutorial for publishing [C++ code on pyPI](https://thomastrapp.com/blog/building-a-pypi-package-for-a-modern-cpp-project/)

**Comment by StRigaud** [comment]
Also more info on distribution for wheel and conda with skbuild and pybind11 here:
- https://github.com/pybind/scikit_build_example

**Comment by StRigaud** [comment]
pipy deployement started to be explored here:
- #23 

It rely on `cibuildwheel` which compile wheel for multiple python version. OS, and architecture, and we can automatically ship them to pipy.
Full wheel CI can be found [here](https://github.com/clEsperanto/pyclesperanto/blob/development/.github/workflows/wheels.yml).

Current issue:
- On Linux, icd-loader is not found. If you look at how pyopencl ppl did, we can see that they rely on the [ocl-icd repo](https://github.com/OCL-dev/ocl-icd) with a [twist](https://github.com/isuruf/ocl-icd/commit/3862386b51930f95d9ad1089f7157a98165d5a6b.patch)
- On Windows, for now `cibuidlwheel` fail during CI at setup. something is missing most likely.
- On MaxOS, all seems to work good. Need to actually test a proper `pip install ....` to be sure.

Additionnal:
To reach this points, several distribution and architecture where skipped. More investigation will be needed later on. For now we apply the KISS methods.

**Comment by haesleinhuepf** [comment]
I just saw this @StRigaud 🎉 

![image](https://user-images.githubusercontent.com/12660498/187442090-5ac81fba-98f2-4452-8bcf-980368fe93b1.png)

**Comment by StRigaud** [comment]
Not ready yet but yeah, it works 🚀 
Still have a small issue with windows wheel but should be fix soon

**Comment by StRigaud** [comment]
`pip install` is set up now and should work fine though more test should be done at some point.
FYI new wheel will only be pushed when a new tag release is setup.

Next step is a conda recipe. I suppose we will have to pass by conda-forge.
@haesleinhuepf if you have any starter doc or procedure / example for me to look at that would be great.

**Comment by StRigaud** [comment]
Started to look in conda recipe:
- https://github.com/StRigaud/staged-recipes/tree/pyclesperanto-feedstock

For now it build and run test locally on my setup. Though not sure it is properly made and that all dependency are good, My experience tells me that it is not :wink: 

Main stuff to verify:
- is OpenCL found at compile time for all OS?
- is OpenCL found at runtime?
- is recipe works with pocl or oclgrind?

If anybody have any insight on this I am happy to take!

**Comment by StRigaud** [comment]
Conda recipe is ready. Waiting for conda-forge to review the recipe and create the feedstock if all is good
- https://github.com/conda-forge/staged-recipes/pull/23908

**Comment by StRigaud** [comment]
conda recipe is done!
