### ISSUE TITLE
Should GPU Image fit to the Numpy API?

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/pyclesperanto#51]
In the following PR 
- #49 
In order to specify the data type we want to manipulate, we are relying on the numpy data type object (e.g. `dtype=np.uint16`). It has the advantages to make things easier for users and developers now used to numpy API.

Similar to this, we started to enable numpy style function with the operators, which allows to call some function as methods (e.g.`my_image.max()`) or arithmetic operations (e.g. `my_image * my_other_image + 3`) 

This raise the question on how much should we fit to the numpy Array API, and what part of the API do we need to develop.

The `Array` class equivalent for pyclesperanto is the [`cleImage` class](https://github.com/clEsperanto/pyclesperanto/blob/enable-dtype-memory/pyclesperanto/_image.py).

**Comment by haesleinhuepf** [comment]
I'm just adding a related issue here: 
* https://github.com/clEsperanto/pyclesperanto_prototype/issues/33

And a link to a project that allows validating numpy-array-compatibility:
* https://github.com/data-apis/array-api-tests

The Array API is huge. I would aim at having basic compatibility (*/+- and some more basic math stuff)

**Comment by StRigaud** [comment]
Thanks, I will look a it!

Basic math and operations are already there, along with the classic `shape`, `ndim`, `dtype`. I do not see any issues in adding possible `reshape`, `dot`, etc. similarly to the `max`, `min` etc.

Indeed maybe not copy all of the API (too much and maybe out of scope).

The question is raised also for the `device` option of Numpy (see [NEP47](https://numpy.org/neps/nep-0047-array-api-standard.html#syntax-for-device-support) and the `asarray`, `get`, methods which is already in used in the prototype version of pyclesperanto.

**Comment by StRigaud** [comment]
New operators have been added to the `Array` class, including `__setitem__` and `__getitem__`.
Array dimension now fit numpy style 

I am pretty sure we are still missing some proper API operator as well as some bug left in how `__setitem__` and `__getitem__` are suppose to behave.
This will  have to be fixed along some proper library testing and feedback.
