### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#60]
The demo notebook for multi-GPU support doesn't work anymore. The API has changed I presume;
https://github.com/clEsperanto/pyclesperanto/blob/main/demos/multi_gpu_demo.ipynb

The error is:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 2
      1 from skimage.io import imread
----> 2 from pyclesperanto import Clesperanto
      3 import time
      4 import numpy as np

ImportError: cannot import name 'Clesperanto' from 'pyclesperanto' (C:\Users\haase\mambaforge\envs\bio39\lib\site-packages\pyclesperanto\__init__.py)
```

Is something like this still supported?

**Comment by StRigaud** [comment]
Nope, this is a relicat of the old design.
Now import is following the same style as the prototype:

```python
import pyclesperanto as cle
```

**Comment by haesleinhuepf** [comment]
But how can have mutliple GPU-handlers at the same time then?

**Comment by haesleinhuepf** [comment]
Ok, I just tried, it doesn't work. The device inside the Processor object is changed/overwritten:

![image](https://user-images.githubusercontent.com/12660498/227525399-e0bc6a51-7386-4000-8b8e-a09f983cb558.png)



Details: https://github.com/clEsperanto/pyclesperanto/blob/a28ad718eec8204fec4571bd743bc798c07e1cd8/demos/test_multigpu.ipynb

**Comment by StRigaud** [comment]
Okay :disappointed: 

However you can still use it as follow:
```python
buffer_rtx = cle.create( (100,100), device=cle.select_device('RTX'))
buffer_gtx = cle.create( (100,100), device=cle.select_device('GTX'))
```
The buffer will hold the correct device has this is handle in the C++ layer.
Same for the kernel call
```python
cle.add_image_and_scalar(src, dst, scalar=1, device=cle.select_device('RTX'))
```
---
For the device managment, I kind of copied what was done in the prototype, see [here](https://github.com/clEsperanto/pyclesperanto/blob/main/pyclesperanto/_device.py). Feel free to make it better! :rocket:

**Comment by StRigaud** [comment]
update following
- #69 

---
### Device selection

Multi device selection can be done as followed:
```python
dev1 = cle.new_device('GTX')
dev2 = cle.new_device('RTX')
```
This approach is not fixed, we might change it in future for a better compatibility with the `select_device()` function.

---
### Memory managment

Pushed images knows which device they are on. Operation on already pushed images will be automatically run on the same device, maintaining coherency.

Mixing Images from different devices will results in a kernel crash, we still need to introduce a runtime error management for this case.

**Comment by StRigaud** [comment]
- https://github.com/clEsperanto/pyclesperanto/blob/main/demos/advance/multi_gpu_demo.ipynb

here is an example on how to use multiple GPU at same time
