### ISSUE TITLE
Device selecting different to the _prototype

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#61]
When running `cle.select_device("")` using pyclesperanto, it selects the first device in the list, which is on my machine a [oclgrind](https://github.com/jrprice/Oclgrind) device emulator. When using `pyclesperanto_prototype`, it select the last device in the list...

**Comment by StRigaud** [comment]
We should also be able to specify the device type we want (cpu, gpu, all) to prevent possible mixup with devices that do both :apple:

**Comment by StRigaud** [comment]
Could we define what should be the default device selection process?
Does this really matters?

:wave:  @haesleinhuepf

**Comment by haesleinhuepf** [comment]
i think the prototype selects the last device per default. Could we have the same behaviour here?

**Comment by StRigaud** [comment]
Ok! I though it was already the case, but there was a flaw in the logic. Should be fixed with the coming release
