### ISSUE TITLE
Default output of a cle image/buffer should be human readable

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#62]
When executing code such as `cle.binary_not([[1,0]])` in a jupyter notebook, I would expect an output such as:
```
[[0,1]]
```

But the output is:
```
<pyclesperanto object cle::Image buffer(float),shape=(1, 1, 2)>
```

This could be fixed by implementing the `__str__` function in the pyclesperanto object class:
* https://github.com/inducer/pyopencl/blob/95ad30e2d4ec8a1ed31f1f16b9efd94829c8f89b/pyopencl/array.py#L970

And/or `_repr_html_`:
* https://github.com/clEsperanto/pyclesperanto_prototype/blob/ea84c9fb11484d3682daee57316518e64ae0ffe8/pyclesperanto_prototype/_tier0/_array_operators.py#L419

**Comment by StRigaud** [comment]
I can have a look at this.

But won`t this mean a `pull` call? I assume this ok because notebook though...

**Comment by StRigaud** [comment]
I will see but I believe we should keep the dtype info as well as add the device name and if buffer or image in the output display.
a bit same as numpy also provide the dtype when printing them

**Comment by StRigaud** [comment]
This should be fixed by:
- #69 

It imply a `pull` from the GPU but `print()` an Image now will also display its content. See the [Image API demos](https://github.com/clEsperanto/pyclesperanto/blob/main/demos/image_API.ipynb)
