### ISSUE TITLE
Edge finding capabilities?

### ISSUE THREAD

**Issue by wuziqi-cmu** [clEsperanto/pyclesperanto#80]
As the title describes, does pyclesperanto has edge finding capabilities? I know skimage has it, but if I can stay within pyclesperanto for my whole workflow, it would be great. :)

**Comment by StRigaud** [comment]
Hello @wuziqi-cmu 

Currently, only Sobel filters and gradient along x, y, and z are available.

More is to come soon!

However if you need more complet library, we still advise for now to use the "prototype" version of pyclesperanto.

```
pip install pyclesperanto-prototype
```
And imported as:
```
import pyclesperanto_prototype as cle 
```

**Comment by StRigaud** [comment]
I'm closing the issue as there is no more discussion, fill free to reopen if needed
