### ISSUE TITLE
`imshow` with gif file display using (xyz) convention

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/pyclesperanto#88]
'imshow' plot the gif image using the (xyz) convention instead of the (zyx). This gives us squished blobs :sob: 

![image](https://github.com/clEsperanto/pyclesperanto/assets/811146/fb430f1b-b0a7-4d77-a34f-f0b847484dbe)

- Possible same issue in the `prototype`
- work fine if something else than `gif`

Found by @CherifMZ

**Comment by haesleinhuepf** [comment]
Hey @StRigaud and @CherifMZ ,

this is also an issue of blobs.gif itself. It's a grey image that's saved as RGB.

Consider using https://samples.fiji.sc/blobs.png instead ([full example](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/basics/count_blobs.ipynb)) as workaround.
