### ISSUE TITLE
Function name aliases

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto#90]
It might be useful to define function aliases. For example, some folks use `cle.connected_component_labeling_box()` and others use `cle.label()`. Both are technically the same as defined [here](https://github.com/clEsperanto/pyclesperanto_prototype/blob/efb38e99984b38ecf3141a63372989cee154958b/pyclesperanto_prototype/_tier4/__init__.py#L3). These aliases are good for backwards compatibility. The question is, shall we have them on CLIc level, too?

**Comment by StRigaud** [comment]
Its easier to make then in the wrapper level eventhough there is a repetition.

If at the CLIc then we would also wrap 2 time the same function. For python its a simple `as` , for java we can simply override.

see
- #91

**Comment by StRigaud** [comment]
Aliases are, for now, taken care of in the `__init__.py` file
